### ISSUE TITLE
Android 4.1 - java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by luccascorrea** [RNCryptor/JNCryptor#26]
On Android 4.1 and below, I can't seem to use the JNCryptor library. I get errors like this one below:

```
  05-06 19:35:47.453  27664-27664/? I/dalvikvm﹕ Could not find method org.cryptonode.jncryptor.Validate.notNull, referenced from method org.cryptonode.jncryptor.AES256JNCryptorOutputStream.<init>
  05-06 19:35:47.453  27664-27664/? W/dalvikvm﹕ VFY: unable to resolve static method 60559: Lorg/cryptonode/jncryptor/Validate;.notNull (Ljava/lang/Object;Ljava/lang/String;[Ljava/lang/Object;)V
  05-06 19:35:47.453  27664-27664/? D/dalvikvm﹕ VFY: replacing opcode 0x71 at 0x0008
  05-06 19:35:47.453  27664-27664/? I/dalvikvm﹕ Could not find method org.cryptonode.jncryptor.Validate.notNull, referenced from method org.cryptonode.jncryptor.AES256JNCryptorOutputStream.<init>
  05-06 19:35:47.453  27664-27664/? W/dalvikvm﹕ VFY: unable to resolve static method 60559: Lorg/cryptonode/jncryptor/Validate;.notNull (Ljava/lang/Object;Ljava/lang/String;[Ljava/lang/Object;)V
  05-06 19:35:47.453  27664-27664/? D/dalvikvm﹕ VFY: replacing opcode 0x71 at 0x000b
  05-06 19:35:47.453  27664-27664/? E/dalvikvm﹕ Could not find class 'org.cryptonode.jncryptor.AES256JNCryptorOutputStream$MacOutputStream', referenced from method org.cryptonode.jncryptor.AES256JNCryptorOutputStream.createStreams
  05-06 19:35:47.453  27664-27664/? W/dalvikvm﹕ VFY: unable to resolve new-instance 8174 (Lorg/cryptonode/jncryptor/AES256JNCryptorOutputStream$MacOutputStream;) in Lorg/cryptonode/jncryptor/AES256JNCryptorOutputStream;
  05-06 19:35:47.453  27664-27664/? D/dalvikvm﹕ VFY: replacing opcode 0x22 at 0x001a
  05-06 19:35:47.469  27664-27664/? I/dalvikvm﹕ Could not find method org.cryptonode.jncryptor.AES256JNCryptorOutputStream$MacOutputStream.write, referenced from method org.cryptonode.jncryptor.AES256JNCryptorOutputStream.writeHeader
  05-06 19:35:47.469  27664-27664/? W/dalvikvm﹕ VFY: unable to resolve virtual method 60507: Lorg/cryptonode/jncryptor/AES256JNCryptorOutputStream$MacOutputStream;.write (I)V
  05-06 19:35:47.469  27664-27664/? D/dalvikvm﹕ VFY: replacing opcode 0x6e at 0x0007
  05-06 19:35:47.469  27664-27664/? I/dalvikvm﹕ Could not find method org.cryptonode.jncryptor.AES256JNCryptorOutputStream$MacOutputStream.write, referenced from method org.cryptonode.jncryptor.AES256JNCryptorOutputStream.writeHeader
  05-06 19:35:47.469  27664-27664/? W/dalvikvm﹕ VFY: unable to resolve virtual method 60507: Lorg/cryptonode/jncryptor/AES256JNCryptorOutputStream$MacOutputStream;.write (I)V
  05-06 19:35:47.469  27664-27664/? D/dalvikvm﹕ VFY: replacing opcode 0x6e at 0x0028
  05-06 19:35:47.469  27664-27664/? D/dalvikvm﹕ DexOpt: unable to opt direct call 0xec5a at 0x1c in Lorg/cryptonode/jncryptor/AES256JNCryptorOutputStream;.createStreams
  05-06 19:35:47.469  27664-27664/? D/AndroidRuntime﹕ Shutting down VM
  05-06 19:35:47.469  27664-27664/? W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0xa622b288)
  05-06 19:35:47.469  27664-27664/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
      java.lang.NoClassDefFoundError: org.cryptonode.jncryptor.Validate
              at org.cryptonode.jncryptor.AES256JNCryptorOutputStream.<init>(AES256JNCryptorOutputStream.java:57)
              at br.com.estudio89.rhmais.core.CustomApplication.onCreate(CustomApplication.java:29)
              at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:999)
              at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4151)
              at android.app.ActivityThread.access$1300(ActivityThread.java:130)
              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1255)
              at android.os.Handler.dispatchMessage(Handler.java:99)
              at android.os.Looper.loop(Looper.java:137)
              at android.app.ActivityThread.main(ActivityThread.java:4745)
              at java.lang.reflect.Method.invokeNative(Native Method)
              at java.lang.reflect.Method.invoke(Method.java:511)
              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
              at dalvik.system.NativeStart.main(Native Method)
```

I noticed that the NoClassDefFoundError only happens with classes that are private to the library, I don't know if Android has any problem with this. I ran the exact same code on Android 5.0+ and it works perfectly.

If anyone would give me a hand with this I would greatly appreciate it, as I have been struggling with this for a couple days and I ran out of ideas of what to do.

Thanks

**Comment by dmjones500** [comment]
Closing due to age. Please reopen if still an issue.
