### ISSUE TITLE
org.cryptonode.jncryptor.InvalidHMACException: Incorrect HMAC value

### ISSUE THREAD

**Issue by thomas2977** [RNCryptor/JNCryptor#33]
I'm encrypting the data in Obj C and decrypting it in Java.
## iOS Code to encrypt:

```
NSString *message = @"Hello World";
NSLog(@"message %@", message);

NSData *data = [message dataUsingEncoding:NSUTF8StringEncoding];
NSString *password = @"secret8888656756secret8888656756";//tried 'secret' and 'secretsquirrell'

NSError *encryptionError = nil;
NSData *cipherData = [RNEncryptor encryptData:data withSettings:kRNCryptorAES128Settings password:password error:&encryptionError];
```
## Java code to decrypt:

```
String password = "secret8888656756secret8888656756";
AES256JNCryptor cryptor = new AES256JNCryptor();

public String decrypt(byte[] encryptedData) {
    byte[] decryptData = null;
    try {
        decryptData = cryptor.decryptData(encryptedData,
                password.toCharArray());
    } catch (CryptorException e) {
        // TODO Auto-generated catch block
        e.printStackTrace();
    }
    return new String(decryptData, Charset.forName("UTF-8"));
}
```
## I'm getting the below error when decrypting encrypted data:

org.cryptonode.jncryptor.InvalidHMACException: Incorrect HMAC value.
        at org.cryptonode.jncryptor.AES256JNCryptor.decryptV3Data(AES256JNCryptor.java:248)
        at org.cryptonode.jncryptor.AES256JNCryptor.decryptV3Data(AES256JNCryptor.java:323)
        at org.cryptonode.jncryptor.AES256JNCryptor.decryptData(AES256JNCryptor.java:280)
        at com.fitzroy.cryptography.JNCryptor.decrypt(JNCryptor.java:29)
        at com.fitzroy.service.CryptographyService.decrypt(CryptographyService.java:62)
        at com.fitzroy.FitzroyResource.decrypt(FitzroyResource.java:58)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)

Please can you let me know if I'm doing anything wrong.

**Comment by rnapier** [comment]
This is almost always due to data corruption when transferring from one system to the other. Make sure that the bytes in `cipherData` are precisely the same bytes as in `encryptedData`. A common version of this problem is when people assume that Base64-encoded data is the same as raw bytes.
